version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./news:/news
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py test &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./news/.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./news/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A news worker -l info
    volumes:
      - ./news:/news
    env_file:
      - ./news/.env.dev
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build:
      context: .
    command: celery -A news beat -l info
    volumes:
      - ./news:/news
    links:
      - celery
      - redis
    depends_on:
      - celery
      - redis
volumes:
  pgdata: